"""empty message

Revision ID: 90f6215938d1
Revises: a22734b5a382
Create Date: 2022-08-10 18:31:02.453784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f6215938d1'
down_revision = 'a22734b5a382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('phone', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'phone')
    # ### end Alembic commands ###
